//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_popytka_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Настройка_теста.
    /// </summary>
    // *** Start programmer edit section *** (Настройка_теста CustomAttributes)

    // *** End programmer edit section *** (Настройка_теста CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Настройка_тестаE", new string[] {
            "Название_Теста as \'Название_ теста\'",
            "Код as \'Код\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Отчество as \'Отчество\'"}, Hidden=new string[] {
            "Сотрудники.Отчество"})]
    [AssociatedDetailViewAttribute("Настройка_тестаE", "Тч2", "Тч2E", true, "", "Тч2", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("Настройка_тестаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Отчество")]
    [View("Настройка_тестаL", new string[] {
            "Название_Теста as \'Название_ теста\'",
            "Код as \'Код\'",
            "Сотрудники.Отчество as \'Отчество\'"})]
    public class Настройка_теста : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание_Теста;
        
        private int fКод;
        
        private IIS.Generaciya_popytka_1.Сотрудники fСотрудники;
        
        private IIS.Generaciya_popytka_1.DetailArrayOfТч2 fТч2;
        
        // *** Start programmer edit section *** (Настройка_теста CustomMembers)

        // *** End programmer edit section *** (Настройка_теста CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Настройка_теста.Код CustomAttributes)

        // *** End programmer edit section *** (Настройка_теста.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Настройка_теста.Код Get start)

                // *** End programmer edit section *** (Настройка_теста.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Настройка_теста.Код Get end)

                // *** End programmer edit section *** (Настройка_теста.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Настройка_теста.Код Set start)

                // *** End programmer edit section *** (Настройка_теста.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Настройка_теста.Код Set end)

                // *** End programmer edit section *** (Настройка_теста.Код Set end)
            }
        }
        
        /// <summary>
        /// Название_Теста.
        /// </summary>
        // *** Start programmer edit section *** (Настройка_теста.Название_Теста CustomAttributes)

        // *** End programmer edit section *** (Настройка_теста.Название_Теста CustomAttributes)
        [StrLen(255)]
        public virtual string Название_Теста
        {
            get
            {
                // *** Start programmer edit section *** (Настройка_теста.Название_Теста Get start)

                // *** End programmer edit section *** (Настройка_теста.Название_Теста Get start)
                string result = this.fНазвание_Теста;
                // *** Start programmer edit section *** (Настройка_теста.Название_Теста Get end)

                // *** End programmer edit section *** (Настройка_теста.Название_Теста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Настройка_теста.Название_Теста Set start)

                // *** End programmer edit section *** (Настройка_теста.Название_Теста Set start)
                this.fНазвание_Теста = value;
                // *** Start programmer edit section *** (Настройка_теста.Название_Теста Set end)

                // *** End programmer edit section *** (Настройка_теста.Название_Теста Set end)
            }
        }
        
        /// <summary>
        /// Настройка_теста.
        /// </summary>
        // *** Start programmer edit section *** (Настройка_теста.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Настройка_теста.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Generaciya_popytka_1.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Настройка_теста.Сотрудники Get start)

                // *** End programmer edit section *** (Настройка_теста.Сотрудники Get start)
                IIS.Generaciya_popytka_1.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Настройка_теста.Сотрудники Get end)

                // *** End programmer edit section *** (Настройка_теста.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Настройка_теста.Сотрудники Set start)

                // *** End programmer edit section *** (Настройка_теста.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Настройка_теста.Сотрудники Set end)

                // *** End programmer edit section *** (Настройка_теста.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Настройка_теста.
        /// </summary>
        // *** Start programmer edit section *** (Настройка_теста.Тч2 CustomAttributes)

        // *** End programmer edit section *** (Настройка_теста.Тч2 CustomAttributes)
        public virtual IIS.Generaciya_popytka_1.DetailArrayOfТч2 Тч2
        {
            get
            {
                // *** Start programmer edit section *** (Настройка_теста.Тч2 Get start)

                // *** End programmer edit section *** (Настройка_теста.Тч2 Get start)
                if ((this.fТч2 == null))
                {
                    this.fТч2 = new IIS.Generaciya_popytka_1.DetailArrayOfТч2(this);
                }
                IIS.Generaciya_popytka_1.DetailArrayOfТч2 result = this.fТч2;
                // *** Start programmer edit section *** (Настройка_теста.Тч2 Get end)

                // *** End programmer edit section *** (Настройка_теста.Тч2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Настройка_теста.Тч2 Set start)

                // *** End programmer edit section *** (Настройка_теста.Тч2 Set start)
                this.fТч2 = value;
                // *** Start programmer edit section *** (Настройка_теста.Тч2 Set end)

                // *** End programmer edit section *** (Настройка_теста.Тч2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Настройка_тестаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Настройка_тестаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Настройка_тестаE", typeof(IIS.Generaciya_popytka_1.Настройка_теста));
                }
            }
            
            /// <summary>
            /// "Настройка_тестаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Настройка_тестаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Настройка_тестаL", typeof(IIS.Generaciya_popytka_1.Настройка_теста));
                }
            }
        }
    }
}
