//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_popytka_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список_ сотрудников_для_прохождения_теста.
    /// </summary>
    // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста CustomAttributes)

    // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Список_Сотрудников_для_прохождения_тестаE", new string[] {
            "Дата as \'Дата\'",
            "Настройка_теста as \'Настройка_теста\'",
            "Настройка_теста.Название_Теста as \'Название_ теста\'"}, Hidden=new string[] {
            "Настройка_теста.Название_Теста"})]
    [MasterViewDefineAttribute("Список_Сотрудников_для_прохождения_тестаE", "Настройка_теста", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название_Теста")]
    public class Список_Сотрудников_для_прохождения_теста : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Generaciya_popytka_1.Настройка_теста fНастройка_теста;
        
        private IIS.Generaciya_popytka_1.Тч2 fТч2;
        
        // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста CustomMembers)

        // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата CustomAttributes)

        // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Get start)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Get end)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Set start)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Set end)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Дата Set end)
            }
        }
        
        /// <summary>
        /// Список_ сотрудников_для_прохождения_теста.
        /// </summary>
        // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста CustomAttributes)

        // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста CustomAttributes)
        [PropertyStorage(new string[] {
                "Настройка_теста"})]
        [NotNull()]
        public virtual IIS.Generaciya_popytka_1.Настройка_теста Настройка_теста
        {
            get
            {
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Get start)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Get start)
                IIS.Generaciya_popytka_1.Настройка_теста result = this.fНастройка_теста;
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Get end)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Set start)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Set start)
                this.fНастройка_теста = value;
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Set end)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Настройка_теста Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya_popytka_1.Тч2.
        /// </summary>
        // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 CustomAttributes)

        // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Тч2"})]
        public virtual IIS.Generaciya_popytka_1.Тч2 Тч2
        {
            get
            {
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Get start)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Get start)
                IIS.Generaciya_popytka_1.Тч2 result = this.fТч2;
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Get end)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Set start)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Set start)
                this.fТч2 = value;
                // *** Start programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Set end)

                // *** End programmer edit section *** (Список_Сотрудников_для_прохождения_теста.Тч2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Список_Сотрудников_для_прохождения_тестаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Список_Сотрудников_для_прохождения_тестаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Список_Сотрудников_для_прохождения_тестаE", typeof(IIS.Generaciya_popytka_1.Список_Сотрудников_для_прохождения_теста));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Список_Сотрудников_для_прохождения_теста.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСписок_Сотрудников_для_прохождения_теста CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСписок_Сотрудников_для_прохождения_теста CustomAttributes)
    public class DetailArrayOfСписок_Сотрудников_для_прохождения_теста : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya_popytka_1.DetailArrayOfСписок_Сотрудников_для_прохождения_теста members)

        // *** End programmer edit section *** (IIS.Generaciya_popytka_1.DetailArrayOfСписок_Сотрудников_для_прохождения_теста members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Список_Сотрудников_для_прохождения_теста by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Список_Сотрудников_для_прохождения_теста.
        /// </summary>
        public DetailArrayOfСписок_Сотрудников_для_прохождения_теста(IIS.Generaciya_popytka_1.Тч2 fТч2) : 
                base(typeof(Список_Сотрудников_для_прохождения_теста), ((ICSSoft.STORMNET.DataObject)(fТч2)))
        {
        }
        
        public IIS.Generaciya_popytka_1.Список_Сотрудников_для_прохождения_теста this[int index]
        {
            get
            {
                return ((IIS.Generaciya_popytka_1.Список_Сотрудников_для_прохождения_теста)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya_popytka_1.Список_Сотрудников_для_прохождения_теста dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
