//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_popytka_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч2.
    /// </summary>
    // *** Start programmer edit section *** (Тч2 CustomAttributes)

    // *** End programmer edit section *** (Тч2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Тч2E", new string[] {
            "Вопрос as \'Вопрос\'",
            "ВариантОт1 as \'Вариант ответа 1\'",
            "ВариантОт2 as \'Вариант ответа 2\'",
            "ВариантОт3 as \'Вариант ответа 3\'"})]
    public class Тч2 : ICSSoft.STORMNET.DataObject
    {
        
        private int fВариантОт1;
        
        private int fВариантОт3;
        
        private string fВопрос;
        
        private int fВариантОт2;
        
        private IIS.Generaciya_popytka_1.Сотрудники fСотрудники;
        
        private IIS.Generaciya_popytka_1.DetailArrayOfСписок_Сотрудников_для_прохождения_теста fСписок_Сотрудников_для_прохождения_теста;
        
        private IIS.Generaciya_popytka_1.Настройка_теста fНастройка_теста;
        
        // *** Start programmer edit section *** (Тч2 CustomMembers)

        // *** End programmer edit section *** (Тч2 CustomMembers)

        
        /// <summary>
        /// ВариантОт1.
        /// </summary>
        // *** Start programmer edit section *** (Тч2.ВариантОт1 CustomAttributes)

        // *** End programmer edit section *** (Тч2.ВариантОт1 CustomAttributes)
        public virtual int ВариантОт1
        {
            get
            {
                // *** Start programmer edit section *** (Тч2.ВариантОт1 Get start)

                // *** End programmer edit section *** (Тч2.ВариантОт1 Get start)
                int result = this.fВариантОт1;
                // *** Start programmer edit section *** (Тч2.ВариантОт1 Get end)

                // *** End programmer edit section *** (Тч2.ВариантОт1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч2.ВариантОт1 Set start)

                // *** End programmer edit section *** (Тч2.ВариантОт1 Set start)
                this.fВариантОт1 = value;
                // *** Start programmer edit section *** (Тч2.ВариантОт1 Set end)

                // *** End programmer edit section *** (Тч2.ВариантОт1 Set end)
            }
        }
        
        /// <summary>
        /// ВариантОт2.
        /// </summary>
        // *** Start programmer edit section *** (Тч2.ВариантОт2 CustomAttributes)

        // *** End programmer edit section *** (Тч2.ВариантОт2 CustomAttributes)
        public virtual int ВариантОт2
        {
            get
            {
                // *** Start programmer edit section *** (Тч2.ВариантОт2 Get start)

                // *** End programmer edit section *** (Тч2.ВариантОт2 Get start)
                int result = this.fВариантОт2;
                // *** Start programmer edit section *** (Тч2.ВариантОт2 Get end)

                // *** End programmer edit section *** (Тч2.ВариантОт2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч2.ВариантОт2 Set start)

                // *** End programmer edit section *** (Тч2.ВариантОт2 Set start)
                this.fВариантОт2 = value;
                // *** Start programmer edit section *** (Тч2.ВариантОт2 Set end)

                // *** End programmer edit section *** (Тч2.ВариантОт2 Set end)
            }
        }
        
        /// <summary>
        /// ВариантОт3.
        /// </summary>
        // *** Start programmer edit section *** (Тч2.ВариантОт3 CustomAttributes)

        // *** End programmer edit section *** (Тч2.ВариантОт3 CustomAttributes)
        public virtual int ВариантОт3
        {
            get
            {
                // *** Start programmer edit section *** (Тч2.ВариантОт3 Get start)

                // *** End programmer edit section *** (Тч2.ВариантОт3 Get start)
                int result = this.fВариантОт3;
                // *** Start programmer edit section *** (Тч2.ВариантОт3 Get end)

                // *** End programmer edit section *** (Тч2.ВариантОт3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч2.ВариантОт3 Set start)

                // *** End programmer edit section *** (Тч2.ВариантОт3 Set start)
                this.fВариантОт3 = value;
                // *** Start programmer edit section *** (Тч2.ВариантОт3 Set end)

                // *** End programmer edit section *** (Тч2.ВариантОт3 Set end)
            }
        }
        
        /// <summary>
        /// Вопрос.
        /// </summary>
        // *** Start programmer edit section *** (Тч2.Вопрос CustomAttributes)

        // *** End programmer edit section *** (Тч2.Вопрос CustomAttributes)
        [StrLen(255)]
        public virtual string Вопрос
        {
            get
            {
                // *** Start programmer edit section *** (Тч2.Вопрос Get start)

                // *** End programmer edit section *** (Тч2.Вопрос Get start)
                string result = this.fВопрос;
                // *** Start programmer edit section *** (Тч2.Вопрос Get end)

                // *** End programmer edit section *** (Тч2.Вопрос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч2.Вопрос Set start)

                // *** End programmer edit section *** (Тч2.Вопрос Set start)
                this.fВопрос = value;
                // *** Start programmer edit section *** (Тч2.Вопрос Set end)

                // *** End programmer edit section *** (Тч2.Вопрос Set end)
            }
        }
        
        /// <summary>
        /// Тч2.
        /// </summary>
        // *** Start programmer edit section *** (Тч2.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Тч2.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Generaciya_popytka_1.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Тч2.Сотрудники Get start)

                // *** End programmer edit section *** (Тч2.Сотрудники Get start)
                IIS.Generaciya_popytka_1.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Тч2.Сотрудники Get end)

                // *** End programmer edit section *** (Тч2.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч2.Сотрудники Set start)

                // *** End programmer edit section *** (Тч2.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Тч2.Сотрудники Set end)

                // *** End programmer edit section *** (Тч2.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Тч2.
        /// </summary>
        // *** Start programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста CustomAttributes)

        // *** End programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста CustomAttributes)
        public virtual IIS.Generaciya_popytka_1.DetailArrayOfСписок_Сотрудников_для_прохождения_теста Список_Сотрудников_для_прохождения_теста
        {
            get
            {
                // *** Start programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Get start)

                // *** End programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Get start)
                if ((this.fСписок_Сотрудников_для_прохождения_теста == null))
                {
                    this.fСписок_Сотрудников_для_прохождения_теста = new IIS.Generaciya_popytka_1.DetailArrayOfСписок_Сотрудников_для_прохождения_теста(this);
                }
                IIS.Generaciya_popytka_1.DetailArrayOfСписок_Сотрудников_для_прохождения_теста result = this.fСписок_Сотрудников_для_прохождения_теста;
                // *** Start programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Get end)

                // *** End programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Set start)

                // *** End programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Set start)
                this.fСписок_Сотрудников_для_прохождения_теста = value;
                // *** Start programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Set end)

                // *** End programmer edit section *** (Тч2.Список_Сотрудников_для_прохождения_теста Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya_popytka_1.Настройка_теста.
        /// </summary>
        // *** Start programmer edit section *** (Тч2.Настройка_теста CustomAttributes)

        // *** End programmer edit section *** (Тч2.Настройка_теста CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Настройка_теста"})]
        public virtual IIS.Generaciya_popytka_1.Настройка_теста Настройка_теста
        {
            get
            {
                // *** Start programmer edit section *** (Тч2.Настройка_теста Get start)

                // *** End programmer edit section *** (Тч2.Настройка_теста Get start)
                IIS.Generaciya_popytka_1.Настройка_теста result = this.fНастройка_теста;
                // *** Start programmer edit section *** (Тч2.Настройка_теста Get end)

                // *** End programmer edit section *** (Тч2.Настройка_теста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч2.Настройка_теста Set start)

                // *** End programmer edit section *** (Тч2.Настройка_теста Set start)
                this.fНастройка_теста = value;
                // *** Start programmer edit section *** (Тч2.Настройка_теста Set end)

                // *** End programmer edit section *** (Тч2.Настройка_теста Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Тч2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Тч2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Тч2E", typeof(IIS.Generaciya_popytka_1.Тч2));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Тч2.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТч2 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТч2 CustomAttributes)
    public class DetailArrayOfТч2 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya_popytka_1.DetailArrayOfТч2 members)

        // *** End programmer edit section *** (IIS.Generaciya_popytka_1.DetailArrayOfТч2 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Тч2 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Тч2.
        /// </summary>
        public DetailArrayOfТч2(IIS.Generaciya_popytka_1.Настройка_теста fНастройка_теста) : 
                base(typeof(Тч2), ((ICSSoft.STORMNET.DataObject)(fНастройка_теста)))
        {
        }
        
        public IIS.Generaciya_popytka_1.Тч2 this[int index]
        {
            get
            {
                return ((IIS.Generaciya_popytka_1.Тч2)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya_popytka_1.Тч2 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
